### ISSUE TITLE
excludes 排除不了单文件？

### ISSUE THREAD

**Issue by mrcuix** [gorelease/gopack#1]
配置文件 `.gopack.yml`

```
  excludes:
  - \.git
  - \static\test.rar
```

在执行`gopack pack` 或者`gopack all` 后
项目当中的 `\static\test.rar` 文件排除不了，还是打包进去

**Comment by codeskyblue** [comment]
看了下源码，excludes接受的是正则表达式，理论上应该这么写

```
excludes:
- \.git
- static/test.rar
```

后台会这么匹配 

```
^\.git$
^static/test.rar$
```

**Comment by mrcuix** [comment]
@codeskyblue 
使用了你所说的方式， 还是没有把文件排除出来

```
includes:
  - static
excludes:
- \.git
- static/test.rar
```

之前没把`includes`里面的写出来,不好意思 : )
系统是win7 64位,go版本 go1.5rc1
